### ISSUE TITLE
Request delivery order

### ISSUE THREAD

**Issue by FromZeus** [qbeon/webwire-go#15] opened 2018-03-29 18:00 UTC
Currently, requests performed one after the other will arrive at the server in serial order, though the order is broken when in the meanwhile the server is unavailable and the client is trying to reconnect before sending out accumulated requests. I suggest making the client retain the order the requests were initially made in to avoid unsynchronized delivery.

**Comment by romshark** [comment] 2018-03-30 21:14
I was able to reproduce the problem in the chatroom example, yes, accumulation of requests during automatic reconnection does desynchronize the order the requests were created in with the order they 're sent to the server.

The question is whether webwire clients really need to guarantee requests to be sent serially in the same order they were created because of the asynchronous nature of requests.

When you really want multiple requests to be processed by the server in a sequence - you need to perform them synchronously:
```
firstReply, _ := client.Request(...)
// will only be sent when the first reply was received
secondReply, _ := client.Request(...)
```

Though when you want to send those requests asynchronously still preserving their order, then you could include a timestamp in each to identify their location in time, or, in case of the chatroom example, alternatively have a FIFO buffer stacking messages in a queue performing all requests synchronously.

**Comment by romshark** [comment] 2018-12-10 12:24
Closing this issue due to the client implementation being moved to [webwire-go-client](https://github.com/qbeon/webwire-go-client)

**Closed by romshark** 2018-12-10 12:24 UTC
Labels: client feature request, undecided
